services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: german_credit 
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse/
      - ./logs:/var/log/clickhouse-server/
      - ./config/:/etc/clickhouse-server/config/
      - ./users/:/etc/clickhouse-server/users.d/
    network_mode: host
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

